/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student.Forms.Create;

import Student.Forms.Read.ViewStudentNumbers;
import Student.Forms.Read.ViewStudentEmails;
import Student.Entities.ContactDetails;
import Student.Entities.Email;
import Student.Entities.PhoneNumber;
import Student.Entities.Student;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static utilities.Queries.insertRecord;
import utilities.Validation;
import static utilities.Validation.isEmail;

/**
 *
 * @author RICK
 */
public class NewStudentForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewEmployeeForm
     */
    public NewStudentForm() {

        while (this.nList.size() > 0) {
            this.nList.remove(0);
        }
        while (this.eList.size() > 0) {
            this.eList.remove(0);
        }

        this.compList = new ArrayList<>();
        this.compList.add(studentIdTextField_new);
        this.compList.add(firstNameTextField_new);
        this.compList.add(lastNameTextField_new);
        this.compList.add(streetLine1TextField_new);
        this.compList.add(streetLine2TextField_new);
        this.compList.add(cityTextField_new);
        this.compList.add(parishTextField_new);

        initComponents();
        genderError_new.setVisible(false);
    }

    private ArrayList<PhoneNumber> nList = new ArrayList<>();
    private ArrayList<Email> eList = new ArrayList<>();
    private ArrayList<JTextField> compList;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup_new = new javax.swing.ButtonGroup();
        studentIDLabel_new = new javax.swing.JLabel();
        firstNameLabel_new = new javax.swing.JLabel();
        lastNameLabel_new = new javax.swing.JLabel();
        studentIdTextField_new = new javax.swing.JTextField();
        firstNameTextField_new = new javax.swing.JTextField();
        lastNameTextField_new = new javax.swing.JTextField();
        genderPanel_new = new javax.swing.JPanel();
        maleRadioButton_new = new javax.swing.JRadioButton();
        femaleRadioButton_new = new javax.swing.JRadioButton();
        contactDetailsPanel_new = new javax.swing.JPanel();
        streetLine1Label_new = new javax.swing.JLabel();
        streetLine2Label_new = new javax.swing.JLabel();
        streetLine1TextField_new = new javax.swing.JTextField();
        streetLine2TextField_new = new javax.swing.JTextField();
        cityLabel_new = new javax.swing.JLabel();
        parishLabel_new = new javax.swing.JLabel();
        parishTextField_new = new javax.swing.JTextField();
        cityTextField_new = new javax.swing.JTextField();
        phoneNumberLabel_new = new javax.swing.JLabel();
        numberTypeComboBox_new = new javax.swing.JComboBox<>();
        emailLabel_new = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        newPhoneNumberButton_new = new javax.swing.JButton();
        newEmailButton_new = new javax.swing.JButton();
        viewNumberButton_new = new javax.swing.JButton();
        viewEmailButton_new = new javax.swing.JButton();
        phoneNumberTextField_new = new javax.swing.JFormattedTextField();
        exitButton_new = new javax.swing.JButton();
        saveStudentButton_new = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        genderError_new = new javax.swing.JLabel();

        studentIDLabel_new.setText("ID#");

        firstNameLabel_new.setText("First Name");

        lastNameLabel_new.setText("Last Name");

        studentIdTextField_new.setName("Student ID"); // NOI18N
        studentIdTextField_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdTextField_newActionPerformed(evt);
            }
        });

        firstNameTextField_new.setName("First Name"); // NOI18N
        firstNameTextField_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextField_newActionPerformed(evt);
            }
        });

        lastNameTextField_new.setToolTipText("");
        lastNameTextField_new.setName("Last Name"); // NOI18N

        genderPanel_new.setName("Gender Panel"); // NOI18N

        genderButtonGroup_new.add(maleRadioButton_new);
        maleRadioButton_new.setText("Male");

        genderButtonGroup_new.add(femaleRadioButton_new);
        femaleRadioButton_new.setText("Female");

        javax.swing.GroupLayout genderPanel_newLayout = new javax.swing.GroupLayout(genderPanel_new);
        genderPanel_new.setLayout(genderPanel_newLayout);
        genderPanel_newLayout.setHorizontalGroup(
            genderPanel_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genderPanel_newLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maleRadioButton_new)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, genderPanel_newLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(femaleRadioButton_new)
                .addContainerGap())
        );
        genderPanel_newLayout.setVerticalGroup(
            genderPanel_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genderPanel_newLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maleRadioButton_new)
                .addGap(18, 18, 18)
                .addComponent(femaleRadioButton_new)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contactDetailsPanel_new.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Contact Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        contactDetailsPanel_new.setName("Contact Details Panel"); // NOI18N

        streetLine1Label_new.setText("Street Line 1");

        streetLine2Label_new.setText("Street Line 2");

        streetLine1TextField_new.setName("Street Line 1"); // NOI18N
        streetLine1TextField_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetLine1TextField_newActionPerformed(evt);
            }
        });

        streetLine2TextField_new.setName("Street Line 2"); // NOI18N

        cityLabel_new.setText("City");

        parishLabel_new.setText("Parish");

        parishTextField_new.setName("Parish"); // NOI18N

        cityTextField_new.setName("City"); // NOI18N

        phoneNumberLabel_new.setText("Telephone #");

        numberTypeComboBox_new.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobile", "Home", "Work" }));
        numberTypeComboBox_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTypeComboBox_newActionPerformed(evt);
            }
        });

        emailLabel_new.setText("E-Mail");

        emailTextField.setName("Email Field"); // NOI18N

        newPhoneNumberButton_new.setText("Add");
        newPhoneNumberButton_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPhoneNumberButton_newActionPerformed(evt);
            }
        });

        newEmailButton_new.setText("Add");
        newEmailButton_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmailButton_newActionPerformed(evt);
            }
        });

        viewNumberButton_new.setText("View");
        viewNumberButton_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewNumberButton_newActionPerformed(evt);
            }
        });

        viewEmailButton_new.setText("View");
        viewEmailButton_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmailButton_newActionPerformed(evt);
            }
        });

        try {
            phoneNumberTextField_new.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+1 (876)###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        phoneNumberTextField_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextField_newActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contactDetailsPanel_newLayout = new javax.swing.GroupLayout(contactDetailsPanel_new);
        contactDetailsPanel_new.setLayout(contactDetailsPanel_newLayout);
        contactDetailsPanel_newLayout.setHorizontalGroup(
            contactDetailsPanel_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactDetailsPanel_newLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactDetailsPanel_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contactDetailsPanel_newLayout.createSequentialGroup()
                        .addGroup(contactDetailsPanel_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactDetailsPanel_newLayout.createSequentialGroup()
                                .addComponent(streetLine2Label_new)
                                .addGap(18, 18, 18))
                            .addGroup(contactDetailsPanel_newLayout.createSequentialGroup()
                                .addComponent(streetLine1Label_new)
                                .addGap(18, 18, 18)))
                        .addGroup(contactDetailsPanel_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(streetLine1TextField_new, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(streetLine2TextField_new))
                        .addGap(18, 18, 18)
                        .addGroup(contactDetailsPanel_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parishLabel_new)
                            .addComponent(cityLabel_new))
                        .addGap(18, 18, 18)
                        .addGroup(contactDetailsPanel_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parishTextField_new)
                            .addComponent(cityTextField_new)))
                    .addGroup(contactDetailsPanel_newLayout.createSequentialGroup()
                        .addGroup(contactDetailsPanel_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneNumberLabel_new)
                            .addComponent(emailLabel_new))
                        .addGap(18, 18, 18)
                        .addGroup(contactDetailsPanel_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailTextField)
                            .addGroup(contactDetailsPanel_newLayout.createSequentialGroup()
                                .addComponent(phoneNumberTextField_new)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numberTypeComboBox_new, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(contactDetailsPanel_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(contactDetailsPanel_newLayout.createSequentialGroup()
                                .addComponent(newEmailButton_new)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(viewEmailButton_new))
                            .addGroup(contactDetailsPanel_newLayout.createSequentialGroup()
                                .addComponent(newPhoneNumberButton_new)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(viewNumberButton_new)))))
                .addContainerGap())
        );
        contactDetailsPanel_newLayout.setVerticalGroup(
            contactDetailsPanel_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactDetailsPanel_newLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactDetailsPanel_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetLine1Label_new)
                    .addComponent(streetLine1TextField_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityLabel_new)
                    .addComponent(cityTextField_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contactDetailsPanel_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parishLabel_new, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addGroup(contactDetailsPanel_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(streetLine2Label_new)
                        .addComponent(streetLine2TextField_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(parishTextField_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(contactDetailsPanel_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberLabel_new)
                    .addComponent(numberTypeComboBox_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPhoneNumberButton_new)
                    .addComponent(viewNumberButton_new)
                    .addComponent(phoneNumberTextField_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contactDetailsPanel_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel_new)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newEmailButton_new)
                    .addComponent(viewEmailButton_new))
                .addGap(25, 25, 25))
        );

        exitButton_new.setText("EXIT");
        exitButton_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton_newActionPerformed(evt);
            }
        });

        saveStudentButton_new.setText("SAVE");
        saveStudentButton_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStudentButton_newActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        genderError_new.setForeground(new java.awt.Color(255, 51, 51));
        genderError_new.setText("Please Select a Gender");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactDetailsPanel_new, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studentIDLabel_new, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(studentIdTextField_new, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNameLabel_new)
                                    .addComponent(firstNameLabel_new, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameTextField_new)
                                    .addComponent(lastNameTextField_new))))
                        .addGap(63, 63, 63)
                        .addComponent(genderPanel_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderError_new))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitButton_new)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveStudentButton_new)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(genderPanel_new, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentIDLabel_new)
                            .addComponent(studentIdTextField_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameLabel_new)
                            .addComponent(firstNameTextField_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLabel_new)
                            .addComponent(lastNameTextField_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(genderError_new)))
                .addGap(18, 18, 18)
                .addComponent(contactDetailsPanel_new, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton_new)
                    .addComponent(saveStudentButton_new))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextField_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextField_newActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextField_newActionPerformed

    private void streetLine1TextField_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetLine1TextField_newActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetLine1TextField_newActionPerformed

    private void exitButton_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton_newActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitButton_newActionPerformed


    private void newPhoneNumberButton_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPhoneNumberButton_newActionPerformed

        PhoneNumber newNumber = new PhoneNumber();

        if (phoneNumberTextField_new.getText().equals("+1 (876)   -    ")) {
            JOptionPane.showMessageDialog(this, "Cannot add null or incomplete field");
        } else {
            newNumber.setNumberType(numberTypeComboBox_new.getSelectedItem().toString());
            newNumber.setNumber(phoneNumberTextField_new.getText());
            phoneNumberTextField_new.setText(null);
            getNList().add(newNumber);
        }


    }//GEN-LAST:event_newPhoneNumberButton_newActionPerformed

    private void newEmailButton_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmailButton_newActionPerformed

        if (isEmail(emailTextField.getText())) {
            Email newEmail = new Email();
            newEmail.setEmailAddress(emailTextField.getText());
            getEList().add(newEmail);
            emailTextField.setText(null);
        } else if (emailTextField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cannot add null or incomplete field");
        } else {
            JOptionPane.showMessageDialog(this, "Email Invalid");
        }


    }//GEN-LAST:event_newEmailButton_newActionPerformed

    private void saveStudentButton_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStudentButton_newActionPerformed
        Student newStudent = new Student();
        ContactDetails studentDetails = new ContactDetails();
        newStudent.setStudentDetails(studentDetails);

        studentDetails.setEmailList(getEList());
        studentDetails.setNumberList(getNList());

        if (streetLine1TextField_new.getText().trim().isEmpty()) {
            studentDetails.setStreetLine1(null);
        } else {
            studentDetails.setStreetLine1(streetLine1TextField_new.getText());
        }

        if (streetLine2TextField_new.getText().trim().isEmpty()) {
            studentDetails.setStreetLine2(null);
        } else {
            studentDetails.setStreetLine2(streetLine2TextField_new.getText());
        }

        if (cityTextField_new.getText().trim().isEmpty()) {
            studentDetails.setCity(null);
        } else {
            studentDetails.setCity(cityTextField_new.getText());
        }

        if (parishTextField_new.getText().trim().isEmpty()) {
            studentDetails.setParish(null);
        } else {
            studentDetails.setParish(parishTextField_new.getText());
        }

        if (studentIdTextField_new.getText().trim().isEmpty()) {
            newStudent.setStudentID(null);
        } else {
            newStudent.setStudentID(studentIdTextField_new.getText());
        }

        if (firstNameTextField_new.getText().trim().isEmpty()) {
            newStudent.setFirstName(null);
        } else {
            newStudent.setFirstName(firstNameTextField_new.getText());
        }

        if (lastNameTextField_new.getText().trim().isEmpty()) {
            newStudent.setLastName(null);
        } else {
            newStudent.setLastName(lastNameTextField_new.getText());
        }

        if (maleRadioButton_new.isSelected()) {
            newStudent.setGender("Male");
        } else if (femaleRadioButton_new.isSelected()) {
            newStudent.setGender("Female");
        }
        if(!(maleRadioButton_new.isSelected() || femaleRadioButton_new.isSelected())){
            genderPanel_new.setBorder(BorderFactory.createLineBorder(Color.red));
                genderError_new.setVisible(true);
        }
        if (Validation.validate(this)) {
            if (insertRecord(newStudent)) {
                JOptionPane.showMessageDialog(this.getParent(), "Record Saved");

            }
        }
//                
//
//                for (JTextField error : Validation.validate(this)) {
//                    
//                    
//                    error.repaint();
//                }
//                this.dispose();

//        else{
//                Border errorBorder = BorderFactory.createLineBorder(Color.red);
//                
//            }

    }//GEN-LAST:event_saveStudentButton_newActionPerformed


    private void viewNumberButton_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewNumberButton_newActionPerformed
        if (!this.nList.isEmpty()) {
            ViewStudentNumbers viewNumbers = new ViewStudentNumbers(this);
            this.getParent().add(viewNumbers);
            viewNumbers.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No number to display");
        }


    }//GEN-LAST:event_viewNumberButton_newActionPerformed

    private void numberTypeComboBox_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTypeComboBox_newActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTypeComboBox_newActionPerformed

    private void studentIdTextField_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdTextField_newActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIdTextField_newActionPerformed

    private void viewEmailButton_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmailButton_newActionPerformed
        if (!this.eList.isEmpty()) {
            ViewStudentEmails viewEmails = new ViewStudentEmails(this);
            this.getParent().add(viewEmails);
            viewEmails.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No Email address to display");
        }

    }//GEN-LAST:event_viewEmailButton_newActionPerformed

    private void phoneNumberTextField_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberTextField_newActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextField_newActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cityLabel_new;
    private javax.swing.JTextField cityTextField_new;
    private javax.swing.JPanel contactDetailsPanel_new;
    private javax.swing.JLabel emailLabel_new;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton exitButton_new;
    private javax.swing.JRadioButton femaleRadioButton_new;
    private javax.swing.JLabel firstNameLabel_new;
    private javax.swing.JTextField firstNameTextField_new;
    private javax.swing.ButtonGroup genderButtonGroup_new;
    private javax.swing.JLabel genderError_new;
    private javax.swing.JPanel genderPanel_new;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNameLabel_new;
    private javax.swing.JTextField lastNameTextField_new;
    private javax.swing.JRadioButton maleRadioButton_new;
    private javax.swing.JButton newEmailButton_new;
    private javax.swing.JButton newPhoneNumberButton_new;
    private javax.swing.JComboBox<String> numberTypeComboBox_new;
    private javax.swing.JLabel parishLabel_new;
    private javax.swing.JTextField parishTextField_new;
    private javax.swing.JLabel phoneNumberLabel_new;
    private javax.swing.JFormattedTextField phoneNumberTextField_new;
    private javax.swing.JButton saveStudentButton_new;
    private javax.swing.JLabel streetLine1Label_new;
    private javax.swing.JTextField streetLine1TextField_new;
    private javax.swing.JLabel streetLine2Label_new;
    private javax.swing.JTextField streetLine2TextField_new;
    private javax.swing.JLabel studentIDLabel_new;
    private javax.swing.JTextField studentIdTextField_new;
    private javax.swing.JButton viewEmailButton_new;
    private javax.swing.JButton viewNumberButton_new;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the numberList
     */
    public ArrayList<PhoneNumber> getNList() {
        return this.nList;
    }

    /**
     * @return the emailList
     */
    public ArrayList<Email> getEList() {
        return this.eList;
    }

    /**
     * @return the compList
     */
    public ArrayList<JTextField> getCompList() {
        return this.compList;
    }
}
