/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student.Forms.Read;

import Student.Entities.Email;
import Student.Entities.PhoneNumber;
import Student.Entities.Student;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static utilities.Queries.editRecord;
import utilities.Validation;

/**
 *
 * @author RICK
 */
public class ViewStudentForm extends javax.swing.JInternalFrame {

    /**
     * @return the studentIDTextField_view
     */
    public JTextField getStudentIDTextField_view() {
        return studentIDTextField_view;
    }

    public JTextField getfirstNameTextField_view() {
        return firstNameTextField_view;
    }

    public JTextField getLastNameTextField_view() {
        return lastNameTextField_view;
    }

    public String getSelectedGender() {
        if (maleRadioButton_view.isSelected()) {
            return "Male";
        } else if (femaleRadioButton_view.isSelected()) {
            return "Female";
        } else {
            return null;
        }
    }

    public JTextField getStreetLine1TextField_view() {
        return streetLine1TextField_view;
    }

    public JTextField getStreetLine2TextField_view() {
        return streetLine2TextField_view;
    }

    public JTextField getCityTextField_view() {
        return cityTextField_view;
    }

    public JTextField getParishTextField_view() {
        return parishTextField_view;
    }

    /**
     * @param newStudent
     */
    public ViewStudentForm(Student newStudent) {

        initComponents();
        genderError_new.setVisible(false);
        studentIDTextField_view.setText(newStudent.getStudentID());
        firstNameTextField_view.setText(newStudent.getFirstName());
        lastNameTextField_view.setText(newStudent.getLastName());

        if (newStudent.getGender().equals("Male")) {
            maleRadioButton_view.setSelected(true);
        } else if (newStudent.getGender().equals("Female")) {
            femaleRadioButton_view.setSelected(true);
        }

        streetLine1TextField_view.setText(newStudent.getStudentDetails().getStreetLine1());
        streetLine2TextField_view.setText(newStudent.getStudentDetails().getStreetLine2());
        cityTextField_view.setText(newStudent.getStudentDetails().getCity());
        parishTextField_view.setText(newStudent.getStudentDetails().getParish());

        this.setNList(newStudent.getStudentDetails().getNumberList());
        this.setEList(newStudent.getStudentDetails().getEmailList());
        this.stud = newStudent;

        this.compList = new ArrayList<>();
        this.compList.add(studentIDTextField_view);
        this.compList.add(firstNameTextField_view);
        this.compList.add(lastNameTextField_view);
        this.compList.add(streetLine1TextField_view);
        this.compList.add(streetLine2TextField_view);
        this.compList.add(cityTextField_view);
        this.compList.add(parishTextField_view);

    }

    private ArrayList<PhoneNumber> nList;
    private ArrayList<Email> eList;
    private ArrayList<JTextField> compList;
    Student stud;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup_view = new javax.swing.ButtonGroup();
        studentIDLabel_view = new javax.swing.JLabel();
        firstNameLabel_view = new javax.swing.JLabel();
        lastNameLabel_view = new javax.swing.JLabel();
        studentIDTextField_view = new javax.swing.JTextField();
        firstNameTextField_view = new javax.swing.JTextField();
        lastNameTextField_view = new javax.swing.JTextField();
        genderPanel_view = new javax.swing.JPanel();
        femaleRadioButton_view = new javax.swing.JRadioButton();
        maleRadioButton_view = new javax.swing.JRadioButton();
        contactDetailsPanel_view = new javax.swing.JPanel();
        streetLine1Label_view = new javax.swing.JLabel();
        streetLine2Label_view = new javax.swing.JLabel();
        streetLine1TextField_view = new javax.swing.JTextField();
        streetLine2TextField_view = new javax.swing.JTextField();
        cityLabel_view = new javax.swing.JLabel();
        parishLabel_view = new javax.swing.JLabel();
        parishTextField_view = new javax.swing.JTextField();
        cityTextField_view = new javax.swing.JTextField();
        phoneNumberLabel_view = new javax.swing.JLabel();
        numberTypeComboBox_view = new javax.swing.JComboBox<String>();
        emailLabel_view = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        viewNumberButton_view = new javax.swing.JButton();
        viewEmailButton_view = new javax.swing.JButton();
        addNumberButton_view = new javax.swing.JButton();
        addEmailButton_view = new javax.swing.JButton();
        phoneNumberTextField_view = new javax.swing.JFormattedTextField();
        exitButton_view = new javax.swing.JButton();
        saveStudentButton_view = new javax.swing.JButton();
        editButton_view = new javax.swing.JButton();
        deleteButton_view = new javax.swing.JButton();
        genderError_new = new javax.swing.JLabel();

        studentIDLabel_view.setText("ID#");

        firstNameLabel_view.setText("First Name");

        lastNameLabel_view.setText("Last Name");

        studentIDTextField_view.setEditable(false);
        studentIDTextField_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDTextField_viewActionPerformed(evt);
            }
        });

        firstNameTextField_view.setEditable(false);
        firstNameTextField_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextField_viewActionPerformed(evt);
            }
        });

        lastNameTextField_view.setEditable(false);

        genderButtonGroup_view.add(femaleRadioButton_view);
        femaleRadioButton_view.setText("Female");
        femaleRadioButton_view.setEnabled(false);

        genderButtonGroup_view.add(maleRadioButton_view);
        maleRadioButton_view.setText("Male");
        maleRadioButton_view.setEnabled(false);

        javax.swing.GroupLayout genderPanel_viewLayout = new javax.swing.GroupLayout(genderPanel_view);
        genderPanel_view.setLayout(genderPanel_viewLayout);
        genderPanel_viewLayout.setHorizontalGroup(
            genderPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, genderPanel_viewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(femaleRadioButton_view)
                .addContainerGap())
            .addGroup(genderPanel_viewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maleRadioButton_view)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        genderPanel_viewLayout.setVerticalGroup(
            genderPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genderPanel_viewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maleRadioButton_view)
                .addGap(18, 18, 18)
                .addComponent(femaleRadioButton_view)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contactDetailsPanel_view.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Contact Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        streetLine1Label_view.setText("Street Line 1");

        streetLine2Label_view.setText("Street Line 2");

        streetLine1TextField_view.setEditable(false);
        streetLine1TextField_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetLine1TextField_viewActionPerformed(evt);
            }
        });

        streetLine2TextField_view.setEditable(false);

        cityLabel_view.setText("City");

        parishLabel_view.setText("Parish");

        parishTextField_view.setEditable(false);
        parishTextField_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parishTextField_viewActionPerformed(evt);
            }
        });

        cityTextField_view.setEditable(false);

        phoneNumberLabel_view.setText("Telephone #");

        numberTypeComboBox_view.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Home", "Work" }));
        numberTypeComboBox_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTypeComboBox_viewActionPerformed(evt);
            }
        });

        emailLabel_view.setText("E-Mail");

        emailTextField.setEditable(false);
        emailTextField.setName("Email Field"); // NOI18N

        viewNumberButton_view.setText("View");
        viewNumberButton_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewNumberButton_viewActionPerformed(evt);
            }
        });

        viewEmailButton_view.setText("View");
        viewEmailButton_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmailButton_viewActionPerformed(evt);
            }
        });

        addNumberButton_view.setText("Add");
        addNumberButton_view.setEnabled(false);
        addNumberButton_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNumberButton_viewActionPerformed(evt);
            }
        });

        addEmailButton_view.setText("Add");
        addEmailButton_view.setEnabled(false);
        addEmailButton_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmailButton_viewActionPerformed(evt);
            }
        });

        phoneNumberTextField_view.setEditable(false);
        try {
            phoneNumberTextField_view.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+1 (876)###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout contactDetailsPanel_viewLayout = new javax.swing.GroupLayout(contactDetailsPanel_view);
        contactDetailsPanel_view.setLayout(contactDetailsPanel_viewLayout);
        contactDetailsPanel_viewLayout.setHorizontalGroup(
            contactDetailsPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactDetailsPanel_viewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactDetailsPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contactDetailsPanel_viewLayout.createSequentialGroup()
                        .addGroup(contactDetailsPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(contactDetailsPanel_viewLayout.createSequentialGroup()
                                .addComponent(streetLine1Label_view)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(streetLine1TextField_view, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contactDetailsPanel_viewLayout.createSequentialGroup()
                                .addComponent(streetLine2Label_view)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(streetLine2TextField_view)))
                        .addGap(18, 18, 18)
                        .addGroup(contactDetailsPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parishLabel_view)
                            .addComponent(cityLabel_view))
                        .addGap(18, 18, 18)
                        .addGroup(contactDetailsPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parishTextField_view, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(cityTextField_view)))
                    .addGroup(contactDetailsPanel_viewLayout.createSequentialGroup()
                        .addGroup(contactDetailsPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(contactDetailsPanel_viewLayout.createSequentialGroup()
                                .addComponent(emailLabel_view, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(emailTextField))
                            .addGroup(contactDetailsPanel_viewLayout.createSequentialGroup()
                                .addComponent(phoneNumberLabel_view)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(phoneNumberTextField_view, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numberTypeComboBox_view, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(contactDetailsPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactDetailsPanel_viewLayout.createSequentialGroup()
                                .addComponent(addNumberButton_view)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(viewNumberButton_view))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactDetailsPanel_viewLayout.createSequentialGroup()
                                .addComponent(addEmailButton_view)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(viewEmailButton_view)))))
                .addContainerGap())
        );
        contactDetailsPanel_viewLayout.setVerticalGroup(
            contactDetailsPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactDetailsPanel_viewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactDetailsPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetLine1Label_view)
                    .addComponent(streetLine1TextField_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityLabel_view)
                    .addComponent(cityTextField_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contactDetailsPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parishLabel_view, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addGroup(contactDetailsPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(streetLine2Label_view)
                        .addComponent(streetLine2TextField_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(parishTextField_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(contactDetailsPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberLabel_view)
                    .addComponent(numberTypeComboBox_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewNumberButton_view)
                    .addComponent(addNumberButton_view)
                    .addComponent(phoneNumberTextField_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contactDetailsPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel_view)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewEmailButton_view)
                    .addComponent(addEmailButton_view))
                .addGap(25, 25, 25))
        );

        exitButton_view.setText("EXIT");
        exitButton_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton_viewActionPerformed(evt);
            }
        });

        saveStudentButton_view.setText("SAVE");
        saveStudentButton_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStudentButton_viewActionPerformed(evt);
            }
        });

        editButton_view.setText("EDIT");
        editButton_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButton_viewActionPerformed(evt);
            }
        });

        deleteButton_view.setText("DELETE");

        genderError_new.setForeground(new java.awt.Color(255, 51, 51));
        genderError_new.setText("Please Select a Gender");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactDetailsPanel_view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studentIDLabel_view, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(studentIDTextField_view, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameLabel_view, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNameLabel_view))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameTextField_view)
                                    .addComponent(lastNameTextField_view))))
                        .addGap(63, 63, 63)
                        .addComponent(genderPanel_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(genderError_new)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteButton_view)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton_view)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton_view)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveStudentButton_view)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(genderPanel_view, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(studentIDLabel_view)
                                    .addComponent(studentIDTextField_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firstNameLabel_view)
                                    .addComponent(firstNameTextField_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lastNameLabel_view)
                                    .addComponent(lastNameTextField_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(genderError_new)))
                .addGap(18, 18, 18)
                .addComponent(contactDetailsPanel_view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton_view)
                    .addComponent(saveStudentButton_view)
                    .addComponent(editButton_view)
                    .addComponent(deleteButton_view))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextField_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextField_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextField_viewActionPerformed

    private void streetLine1TextField_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetLine1TextField_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetLine1TextField_viewActionPerformed

    private void numberTypeComboBox_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTypeComboBox_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTypeComboBox_viewActionPerformed

    private void parishTextField_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parishTextField_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parishTextField_viewActionPerformed

    private void studentIDTextField_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDTextField_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDTextField_viewActionPerformed

    private void viewNumberButton_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewNumberButton_viewActionPerformed
        // TODO add your handling code here:
        ViewStudentNumbers viewNumbers = new ViewStudentNumbers(this);
        this.getParent().add(viewNumbers);
        viewNumbers.setVisible(true);
    }//GEN-LAST:event_viewNumberButton_viewActionPerformed

    private void viewEmailButton_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmailButton_viewActionPerformed
        // TODO add your handling code here:
        ViewStudentEmails viewEmails = new ViewStudentEmails(this);
        this.getParent().add(viewEmails);
        viewEmails.setVisible(true);
    }//GEN-LAST:event_viewEmailButton_viewActionPerformed

    private void editButton_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButton_viewActionPerformed
        studentIDTextField_view.setEditable(true);
        getFirstNameTextField_view().setEditable(true);
        lastNameTextField_view.setEditable(true);
        maleRadioButton_view.setEnabled(true);
        femaleRadioButton_view.setEnabled(true);

        streetLine1TextField_view.setEditable(true);
        streetLine2TextField_view.setEditable(true);
        cityTextField_view.setEditable(true);
        parishTextField_view.setEditable(true);
        phoneNumberTextField_view.setEditable(true);
        emailTextField.setEditable(true);
        addNumberButton_view.setEnabled(true);
        addEmailButton_view.setEnabled(true);
        numberTypeComboBox_view.setEditable(true);
    }//GEN-LAST:event_editButton_viewActionPerformed

    private void saveStudentButton_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStudentButton_viewActionPerformed
//         TODO add your handling code here:
        if(Validation.validate(this)){
        editRecord(stud, this);
        JOptionPane.showMessageDialog(this.getParent(), "Record Updated");
        this.dispose();  
        }
        
    }//GEN-LAST:event_saveStudentButton_viewActionPerformed

    private void addNumberButton_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNumberButton_viewActionPerformed
        // TODO add your handling code here:
        PhoneNumber newNumber = new PhoneNumber();
        newNumber.setNumberType(numberTypeComboBox_view.getSelectedItem().toString());
        newNumber.setNumber(phoneNumberTextField_view.getText());
        this.nList.add(newNumber);
        phoneNumberTextField_view.setText(null);
    }//GEN-LAST:event_addNumberButton_viewActionPerformed

    private void addEmailButton_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmailButton_viewActionPerformed
        // TODO add your handling code here:
        Email newEmail = new Email();
        newEmail.setEmailAddress(emailTextField.getText());
        eList.add(newEmail);
        emailTextField.setText(null);
    }//GEN-LAST:event_addEmailButton_viewActionPerformed

    private void exitButton_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton_viewActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitButton_viewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmailButton_view;
    private javax.swing.JButton addNumberButton_view;
    private javax.swing.JLabel cityLabel_view;
    private javax.swing.JTextField cityTextField_view;
    private javax.swing.JPanel contactDetailsPanel_view;
    private javax.swing.JButton deleteButton_view;
    private javax.swing.JButton editButton_view;
    private javax.swing.JLabel emailLabel_view;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton exitButton_view;
    private javax.swing.JRadioButton femaleRadioButton_view;
    private javax.swing.JLabel firstNameLabel_view;
    private javax.swing.JTextField firstNameTextField_view;
    private javax.swing.ButtonGroup genderButtonGroup_view;
    private javax.swing.JLabel genderError_new;
    private javax.swing.JPanel genderPanel_view;
    private javax.swing.JLabel lastNameLabel_view;
    private javax.swing.JTextField lastNameTextField_view;
    private javax.swing.JRadioButton maleRadioButton_view;
    private javax.swing.JComboBox<String> numberTypeComboBox_view;
    private javax.swing.JLabel parishLabel_view;
    private javax.swing.JTextField parishTextField_view;
    private javax.swing.JLabel phoneNumberLabel_view;
    private javax.swing.JFormattedTextField phoneNumberTextField_view;
    private javax.swing.JButton saveStudentButton_view;
    private javax.swing.JLabel streetLine1Label_view;
    private javax.swing.JTextField streetLine1TextField_view;
    private javax.swing.JLabel streetLine2Label_view;
    private javax.swing.JTextField streetLine2TextField_view;
    private javax.swing.JLabel studentIDLabel_view;
    private javax.swing.JTextField studentIDTextField_view;
    private javax.swing.JButton viewEmailButton_view;
    private javax.swing.JButton viewNumberButton_view;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the nList
     */
    public ArrayList<PhoneNumber> getNList() {
        return nList;
    }

    /**
     * @param nList the nList to set
     */
    public void setNList(ArrayList<PhoneNumber> nList) {
        this.nList = nList;
    }

    /**
     * @return the eList
     */
    public ArrayList<Email> getEList() {
        return this.eList;
    }

    /**
     * @param eList the eList to set
     */
    public void setEList(ArrayList<Email> eList) {
        this.eList = eList;
    }

    /**
     * @return the firstNameTextField_view
     */
    public javax.swing.JTextField getFirstNameTextField_view() {
        return firstNameTextField_view;
    }

    /**
     * @return the compList
     */
    public ArrayList<JTextField> getCompList() {
        return compList;
    }
}
